Ext.define('UI.model.forms.SirForm', {
    extend: 'Ext.data.Model',
    idProperty: 'id',    
    fields: [
        { name: 'id', type: 'string' },
        { name: 'sirNo', type: 'string' },
        { name: 'sirArea', type: 'string' },
        { name: 'playerId', type: 'string' },
        { name: 'sirMethodVerify', type: 'string' },
        { name: 'sirCurrentRelationship', type: 'string' },
        { name: 'sirAffiliationRelationship', type: 'string' },
        { name: 'sirTypeSuspiciousActivities', type: 'string' },
        { name: 'sirTranDateFrom', type: 'date' },
        { name: 'sirTranDateTo', type: 'date' },
        { name: 'ctrFormId', type: 'string' },
        { name: 'ctrFormNo', type: 'string' },
        { name: 'sirAmount', type: 'float' },
        { name: 'sirSuspiciousIncidence', type: 'string' },
        { name: 'sirWatchlist', type: 'bool' },
        { name: 'sirStaffId', type: 'string' },
        { name: 'sirStaffDepartment', type: 'string' },
        { name: 'sirDocumentNo', type: 'string' },
        { name: 'submission', type: 'bool' },
        { name: 'status', type: 'string' },
        { name: 'recievedDate', type: 'date' },
        { name: 'recievedBy', type: 'string' },
        { name: 'review', type: 'string' },
        { name: 'sirAffiliationRelationshipOthers', type: 'string' },
        { name: 'sirCurrentRelationshipOthers', type: 'string' },
        { name: 'sirTypeSuspiciousActivitiesOthers', type: 'string' },
        { name: 'sirMethodVerifyOthers', type: 'string' },
        { name: 'isConvertToSTR', type: 'bool' },
        { name: 'sirTransactionType', type: 'string' },
        { name: 'playerWith', type: 'string' },
        { name: 'createdDate', type: 'date' },
        { name: 'createdBy', type: 'string' },
        { name: 'modifiedDate', type: 'date' },
        { name: 'modifiedBy', type: 'string' },
        { name: 'playerName', type: 'string' },
        { name: 'playerCardType', type: 'string' },
        { name: 'driverLicense', type: 'string' },
        { name: 'gercCardNo', type: 'string' },
        { name: 'idCard', type: 'string' },
        { name: 'passport', type: 'string' },
        { name: 'others', type: 'string' },
        { name: 'noCard', type: 'string' },
        { name: 'dob', type: 'string' }     
    ]
});