Ext.define('UI.model.forms.StrForm', {
    extend: 'Ext.data.Model',
    idProperty: 'id',    
    fields: [
        { name: 'id', type: 'string' },
        { name: 'strNo', type: 'string' },
        { name: 'sirNo', type: 'string' },
        { name: 'strArea', type: 'string' },
        { name: 'playerId', type: 'string' },
        { name: 'strMethodVerify', type: 'string' },
        { name: 'strCurrentRelationship', type: 'string' },
        { name: 'strAffiliationRelationship', type: 'string' },
        { name: 'strTypeSuspiciousActivities', type: 'string' },
        { name: 'strTranDateFrom', type: 'date' },
        { name: 'strTranDateTo', type: 'date' },
        { name: 'ctrFormId', type: 'string' },
        { name: 'ctrFormNo', type: 'string' },
        { name: 'strAmount', type: 'float' },
        { name: 'strSuspiciousIncidence', type: 'string' },
        { name: 'strWatchlist', type: 'bool' },
        { name: 'strStaffId', type: 'string' },
        { name: 'strStaffDepartment', type: 'string' },
        { name: 'strDocumentNo', type: 'string' },
        { name: 'submission', type: 'bool' },
        { name: 'status', type: 'string' },
        { name: 'recievedDate', type: 'date' },
        { name: 'recievedBy', type: 'string' },
        { name: 'review', type: 'string' },
        { name: 'strAffiliationRelationshipOthers', type: 'string' },
        { name: 'strCurrentRelationshipOthers', type: 'string' },
        { name: 'strTypeSuspiciousActivitiesOthers', type: 'string' },
        { name: 'strMethodVerifyOthers', type: 'string' },
        { name: 'strTransactionType', type: 'string' },
        { name: 'playerWith', type: 'string' },
        { name: 'createdDate', type: 'date' },
        { name: 'createdBy', type: 'string' },
        { name: 'modifiedDate', type: 'date' },
        { name: 'modifiedBy', type: 'string' },
        { name: 'playerName', type: 'string' },
        { name: 'playerCardType', type: 'string' },
        { name: 'driverLicense', type: 'string' },
        { name: 'gercCardNo', type: 'string' },
        { name: 'idCard', type: 'string' },
        { name: 'passport', type: 'string' },
        { name: 'others', type: 'string' },
        { name: 'noCard', type: 'string' },
        { name: 'dob', type: 'string' }     
    ]
});